#!/bin/bash
cd /home/ec2-user/app/

# Instalar Node.js 18.x
sudo dnf install -y curl
curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
sudo dnf install -y nodejs

# Instalar PM2 globalmente
sudo npm install -g pm2

# Instalar dependencias del proyecto
npm install