#!/bin/bash

# Instalar Node.js 18.x
dnf install -y curl
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
dnf install -y nodejs

# (Opcional) Actualizar npm, pero no necesario si usas Node 18
# npm install -g npm@latest --force

# Instalar PM2 globalmente
npm install -g pm2

# Instalar dependencias del proyecto como root
cd /home/ec2-user/app/
npm install --no-audit --no-fund
