#!/bin/bash
cd /home/ec2-user/app/

# Iniciar la aplicación con PM2 y configurar inicio automático como root
pm2 start ecosystem.config.js
pm2 save
pm2 startup systemd --hp /root
systemctl start pm2-root
